language: node_js
node_js:
- '6'
script:
- yarn test
cache: yarn
before_deploy:
- yarn build
deploy:
  provider: npm
  email: contacto@platan.us
  api_key:
    secure: Whetycvx4/RyJbzR5cGIloYCt18D7eXept1uzbR/Us6QrcHPqXp9WOrIO9C/WbXa0oPrS/975lmlLFeUrxt5O+kv4ujgSpBb9yaBtUmYJKMYQhaBQW2MIJGmwTYxBvUbKMGfK/EW3+IV+DUve45r0rrI6IVR59Jx6Q0CmvS5Wvtb7gMgXNFqfMpNtFUFJFftwng1RG8YrlOhj00HbaNcrlKky+DxPfxpVtmeGWv/qPmwUZpH6sFbMDyPgENh8Del+fHoSs2YlpwUpjieDjnRf1hmkpvdkVQ4vug9yiIMtDCDN8D1VBn5jSFvek2Ahhx9jc2rG6nAzmcfpxis43Sz5e64ubpzBW2F4zS0AoKr+OtnioFFPA33Ficd3FvIllz9X7wnpE+259icXxBO87IvKvX9eXOteHjqjRwASrEw7oYRpWq90Zm5LIqG/JWbP7mEzNyW25uHosCBhZXJICq7K3P6IPCp/OXfjodsBXs2XBC3tK03+BkuuNc5rGqCRKH2eQ3XDkk87r//DuuP6Zsd2G2vbL5C77CswAkj/LS8gaOnpbAgjVz+0v2tUpkwmt+9rBrypHvOUEGvTu13CeEap5+uZBhrii3/zBMxynpJAAl0uNwYP0Sjt7Ml9bm7q2ljJd96BgLbx0/ClE24PBwnqGT1gs34KH4PBLykVLfelNg=
  on:
    tags: true
    repo: platanus/ng2-rut
